version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ../backend/
    command: sh -c "alembic revision --autogenerate&&
                    alembic upgrade head &&
                    uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000"
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ../frontend/
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  nginx:
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend
