"""Added author column to Recipe

Revision ID: 0e3e60a86710
Revises: ee39c74b24f5
Create Date: 2024-04-11 15:42:34.402444

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e3e60a86710'
down_revision: Union[str, None] = 'ee39c74b24f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'recipe', sa.Column('author_id', sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, 'recipe', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'author_id')
    # ### end Alembic commands ###
