"""change id to nullable

Revision ID: 357d70dbb450
Revises: 8e3b5a477e80
Create Date: 2024-04-14 18:57:15.835243

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '357d70dbb450'
down_revision: Union[str, None] = '8e3b5a477e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredientsinrecipe', 'pk_id')
    op.add_column(
        'tagsinrecipe',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    )
    op.drop_column('tagsinrecipe', 'pk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tagsinrecipe',
        sa.Column('pk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_column('tagsinrecipe', 'id')
    op.add_column(
        'ingredientsinrecipe',
        sa.Column('pk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
