"""change id to compositekey

Revision ID: 711aa2989a86
Revises: caf83b2d09ec
Create Date: 2024-04-14 20:26:22.549603

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '711aa2989a86'
down_revision: Union[str, None] = 'caf83b2d09ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredientsinrecipe', 'pk_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ingredientsinrecipe',
        sa.Column('pk_id', sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
