"""Add a column

Revision ID: 73534597cb84
Revises: f9a01439060a
Create Date: 2024-04-06 14:37:43.081477

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '73534597cb84'
down_revision: Union[str, None] = 'f9a01439060a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'token',
        sa.Column('token_type', sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'token_type')
    # ### end Alembic commands ###
