"""Return former state

Revision ID: 7ec7f11493b8
Revises: 8b01fc9f5403
Create Date: 2024-04-13 23:09:59.418097

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ec7f11493b8'
down_revision: Union[str, None] = '8b01fc9f5403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ingredient',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('measurement_unit', sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'tag',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('color', sa.String(length=7), nullable=False),
        sa.Column('slug', sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug'),
    )
    op.create_table(
        'ingredientsinrecipe',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('recipe_id', sa.Integer(), nullable=False),
        sa.Column('ingredient_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['ingredient_id'],
            ['ingredient.id'],
        ),
        sa.ForeignKeyConstraint(
            ['recipe_id'],
            ['recipe.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('recipe_id', 'ingredient_id'),
    )
    op.create_table(
        'tagsinrecipe',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('recipe_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['recipe_id'],
            ['recipe.id'],
        ),
        sa.ForeignKeyConstraint(
            ['tag_id'],
            ['tag.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('recipe_id', 'tag_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tagsinrecipe')
    op.drop_table('ingredientsinrecipe')
    op.drop_table('tag')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
