"""Add association proxy to TagInRecipe

Revision ID: 8e3b5a477e80
Revises: d6c5e4632d46
Create Date: 2024-04-14 16:42:08.305576

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8e3b5a477e80'
down_revision: Union[str, None] = 'd6c5e4632d46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tagsinrecipe',
        sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    )
    op.drop_column('tagsinrecipe', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tagsinrecipe',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_column('tagsinrecipe', 'pk_id')
    # ### end Alembic commands ###
