"""change id TagsinRecipe  to compositekey

Revision ID: c07d2a64da02
Revises: 711aa2989a86
Create Date: 2024-04-14 20:29:07.497569

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c07d2a64da02'
down_revision: Union[str, None] = '711aa2989a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tagsinrecipe', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tagsinrecipe',
        sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
