"""change id to id_pk_init=False

Revision ID: caf83b2d09ec
Revises: ed6fb0aff535
Create Date: 2024-04-14 20:21:00.106464

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'caf83b2d09ec'
down_revision: Union[str, None] = 'ed6fb0aff535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
