"""Add association proxy

Revision ID: d6c5e4632d46
Revises: 7ec7f11493b8
Create Date: 2024-04-14 16:15:45.207071

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6c5e4632d46'
down_revision: Union[str, None] = '7ec7f11493b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ingredientsinrecipe',
        sa.Column('pk_id', sa.Integer(), autoincrement=True, nullable=False),
    )
    op.drop_column('ingredientsinrecipe', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'ingredientsinrecipe',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_column('ingredientsinrecipe', 'pk_id')
    # ### end Alembic commands ###
