"""Deleted rows for checking tables_2

Revision ID: e28b934887aa
Revises: eb2765cabf9c
Create Date: 2024-04-13 22:56:26.591035

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e28b934887aa'
down_revision: Union[str, None] = 'eb2765cabf9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'recipe', sa.Column('author_id', sa.Integer(), nullable=False)
    )
    op.create_foreign_key(None, 'recipe', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'author_id')
    # ### end Alembic commands ###
