"""Delete UniqueConstraint

Revision ID: e8809b20fcaf
Revises: c07d2a64da02
Create Date: 2024-04-16 20:35:44.767647

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e8809b20fcaf'
down_revision: Union[str, None] = 'c07d2a64da02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'ingredientsinrecipe_recipe_id_ingredient_id_key',
        'ingredientsinrecipe',
        type_='unique',
    )
    op.drop_constraint(
        'tagsinrecipe_recipe_id_tag_id_key', 'tagsinrecipe', type_='unique'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'tagsinrecipe_recipe_id_tag_id_key',
        'tagsinrecipe',
        ['recipe_id', 'tag_id'],
    )
    op.create_unique_constraint(
        'ingredientsinrecipe_recipe_id_ingredient_id_key',
        'ingredientsinrecipe',
        ['recipe_id', 'ingredient_id'],
    )
    # ### end Alembic commands ###
