"""Deleted rows for checking tables

Revision ID: eb2765cabf9c
Revises: 0e3e60a86710
Create Date: 2024-04-13 22:39:35.184987

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eb2765cabf9c'
down_revision: Union[str, None] = '0e3e60a86710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_author_id_fkey', 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'recipe',
        sa.Column(
            'author_id', sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        'recipe_author_id_fkey', 'recipe', 'user', ['author_id'], ['id']
    )
    # ### end Alembic commands ###
